apiVersion: apps/v1
kind: Deployment
metadata: 
  name: greeting-deploymnet
  labels: 
    app: greeting
spec:
  replicas: 3
  selector:      # defines label selector for pods  
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
      spec: 
        containers: 
          - name: greeting-container
            image: arungupta/greeting
            ports: 
            - containerPort: 8080
    