apiVersion: v1
kind: Service
metadata: 
  name: greeting-service
spec:
  selector:
    app: greeting
  ports: 
  - port: 80   # port to be exposed by the service
    targetPort: 8080   #name or number of the ports to access on the pods targeted by the service